site_name: Higgs-Charm
site_url: https://higgs-charm.docs.cern.ch/
site_author: Nordin Breugelmans
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: 'index.md'
  - Simulation:
      - 'Setting up the repository': 'simulation/setup.md'
      - 'Configuring your process': 'simulation/process.md'
      - 'Gridpack production': 'simulation/gridpack.md'
      - 'Setting up next simulation steps': 'simulation/setup-next-sim-steps.md'
      - 'GEN': 'simulation/GEN.md'
      - 'RAW': 'simulation/RAW.md'
      - 'HLT': 'simulation/HLT.md'
      - 'MINIAOD': 'simulation/MINIAOD.md'
  - 'Higgs + Jet':
      - 'Leading order': 'higgsjet/leading-order.md'
      - 'Next-to-leading order': 'higgsjet/next-to-leading-order.md'

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    - attr_list

extra_css:
  - stylesheets/extra.css
