site_name: Higgs-Charm
site_url: https://higgs-charm.docs.cern.ch/
site_author: Nordin Breugelmans
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: 'index.md'
  - Analysis: 'analysis.md'
  - About: 'about.md'
